version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    command: mongod --quiet
volumes:
  mongodb:
