apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.service.name }}
